// - - - - - - - - - - - - - - - - - - - -
//
// Digimarc Confidential
// Copyright Digimarc Corporation, 2014-2016
//
// - - - - - - - - - - - - - - - - - - - -

#import <Foundation/Foundation.h>

///Represents one item of resolved content. Resolved content can contain more than one item. For example, a package may contain two different user experiences. Each item can contain a different set of properties.
NS_SWIFT_NAME(ResolvedContentItem)
@interface DMSResolvedContentItem : NSObject

/** Optional text to display in the UI such as a list or summary. If this is not defined in the Digimarc Barcode Manager, a synthesized title based on the payload value may be provided.
 */
@property (nonatomic, retain, readonly, nullable) NSString * title;

/** Optional text to display additional information in the UI such as a list or summary. If this is not defined in the Digimarc Barcode Manager, a synthesized title based on the payload value may be provided.
 */
@property (nonatomic, retain, readonly, nullable) NSString * subtitle;

/** Optional URL for an image associated with the resolved content. If not defined in the Digimarc Barcode Manager, this field will be nil.
 */
@property (nonatomic, retain, readonly, nullable) NSURL * thumbnailURL;

/** Optional content URL associated with this resolved content. If this field is not defined in the Digimarc Barcode Manager, a synthesized generic Google search URL may be provided. If no appropriate URL can be provided, this field may be nil.
 */
@property (nonatomic, retain, readonly, nullable) NSURL * URL;

/** Unique token for reporting UI viewing of this payoff content back to the Digimarc Barcode Manager via the resolver's reportAction fuction.
 */
@property (nonatomic, retain, readonly, nullable) NSString * actionToken;

/** Returns true if the content is not active on the Digimarc backend, and this content item is a placeholder item.
 */
@property (nonatomic, readonly) BOOL contentInactive;

/** Indicates whether or not the content was dynamically generated by the resolver. If true, implies that the resolver could not find matching content to service the request, so it generated content to try to fulfill the request.
 */
@property (nonatomic, readonly) BOOL synthesizedContent;

@end
